Exception below was fixed.
org.eclipse.core.internal.resources.ResourceException: Resource '/SimpleEar' does not exist.
     [java] 	at org.eclipse.core.internal.resources.Resource.checkExists(Resource.java:319)
     [java] 	at org.eclipse.core.internal.resources.Resource.checkAccessible(Resource.java:196)
     [java] 	at org.eclipse.core.internal.resources.Project.checkAccessible(Project.java:113)
     [java] 	at org.eclipse.core.internal.resources.Resource.accept(Resource.java:49)
     [java] 	at org.eclipse.wst.validation.internal.ValBuilderJob.fullBuild(ValBuilderJob.java:215)
     [java] 	at org.eclipse.wst.validation.internal.ValBuilderJob.run(ValBuilderJob.java:177)
     [java] 	at org.eclipse.wst.validation.internal.ValBuilderJob.runInWorkspace(ValBuilderJob.java:125)
     [java] 	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:38)
     [java] 	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)


git-svn-id: http://svn.jboss.org/repos/jbosstools/trunk@19858 a97e2381-89e5-4abb-bab3-167db6db766c