Merged revisions 6137-6142 via svnmerge from https://svn.jboss.org/repos/jbosstools/trunk
........
  r6137 | dgolovin | 2008-02-06 23:00:44 +0100 (Wed, 06 Feb 2008) | 1 line
  
  fix errors in testActionHandlers JUnit test
........
  r6138 | dgolovin | 2008-02-06 23:16:02 +0100 (Wed, 06 Feb 2008) | 1 line
  
  fix testJiraJbide1631	error: Failure Marker matches the '"foo1" cannot be resolved' pattern wasn't found
........
  r6139 | dgolovin | 2008-02-07 02:13:52 +0100 (Thu, 07 Feb 2008) | 1 line
  
  fix for hibernate console tests errors
........
  r6140 | dgolovin | 2008-02-07 03:12:11 +0100 (Thu, 07 Feb 2008) | 1 line
  
  Run test only for xulRunner view with about:blank to understand is it started at all? Since it looks like all errors in VPE tests related to XHTML. Now html and struts tests run without errors, but they have html and jsp files.
........
  r6141 | dgolovin | 2008-02-07 04:55:39 +0100 (Thu, 07 Feb 2008) | 1 line
  
  rollback code for waitForJobs method
........
  r6142 | dgolovin | 2008-02-07 07:15:54 +0100 (Thu, 07 Feb 2008) | 1 line
  
  fix compilation error
........


git-svn-id: http://svn.jboss.org/repos/jbosstools/branches/jbosstools-2.0.x@6150 a97e2381-89e5-4abb-bab3-167db6db766c