use antrun 1.7 instead of 1.3 to hopefully work around 'Execution install of goal org.apache.maven.plugins:maven-antrun-plugin:1.3:run failed: An API incompatibility was encountered while executing org.apache.maven.plugins:maven-antrun-plugin:1.3:run: java.lang.NoSuchMethodError: org.apache.tools.ant.launch.Locator.fromJarURI(Ljava/lang/String;)Ljava/lang/String'
git-svn-id: http://svn.jboss.org/repos/jbosstools/trunk@42321 a97e2381-89e5-4abb-bab3-167db6db766c